let entities = [
  {
    html: '&quot;',
    symbol: '"',
    numeric: '&#34;',
    description: 'quotation mar',
    hex: 'u+0022 ISOnum',
    cssIso: '\\0022',
    jsOctal: '\\42',
    category: 'special characters',
    like: false
  },
  {
    html: '&num;',
    symbol: '#',
    numeric: '&#35;',
    description: 'number sign',
    hex: 'u+0023 ISOnum',
    cssIso: '\\0023',
    jsOctal: '\\43',
    category: 'special characters',
    like: false
  },
  {
    html: '&dollar;',
    symbol: '$',
    numeric: '&#36;',
    description: 'dollar sign',
    hex: 'u+0024 ISOnum',
    cssIso: '\\0024',
    jsOctal: '\\44',
    category: 'special characters',
    like: false
  },
  {
    html: '&percnt;',
    symbol: '%',
    numeric: '&#37;',
    description: 'percent sign',
    hex: 'u+0025 ISOnum',
    cssIso: '\\0025',
    jsOctal: '\\45',
    category: 'special characters',
    like: false
  },
  {
    html: '&amp;',
    symbol: '&',
    numeric: '&#38;',
    description: 'ampersand',
    hex: 'u+0026 ISOnum',
    cssIso: '\\0026',
    jsOctal: '\\46',
    category: 'special characters',
    like: false
  },
  {
    html: '&apos;',
    symbol: "'",
    numeric: '&#39;',
    description: 'apostrophe',
    hex: 'u+0027 ISOnum',
    cssIso: '\\0027',
    jsOctal: '\\47',
    category: 'special characters',
    like: false
  },
  {
    html: '&lpar;',
    symbol: '(',
    numeric: '&#40;',
    description: 'left parenthesis',
    hex: 'u+0028 ISOnum',
    cssIso: '\\0028',
    jsOctal: '\\50',
    category: 'special characters',
    like: false
  },
  {
    html: '&rpar;',
    symbol: ')',
    numeric: '&#41;',
    description: 'right parenthesis',
    hex: 'u+0029 ISOnum',
    cssIso: '\\0029',
    jsOctal: '\\51',
    category: 'special characters',
    like: false
  },
  {
    html: '&ast;',
    symbol: '*',
    numeric: '&#42;',
    description: 'asterisk',
    hex: 'u+002A ISOnum',
    cssIso: '\\002a',
    jsOctal: '\\52',
    category: 'special characters',
    like: false
  },
  {
    html: '&plus;',
    symbol: '+',
    numeric: '&#43;',
    description: 'plus sign',
    hex: 'u+002B ISOnum',
    cssIso: '\\002b',
    jsOctal: '\\53',
    category: 'special characters',
    like: false
  },
  {
    html: '&comma;',
    symbol: ',',
    numeric: '&#44;',
    description: 'comma',
    hex: 'u+002C ISOnum',
    cssIso: '\\002c',
    jsOctal: '\\54',
    category: 'special characters',
    like: false
  },
  {
    html: '&minus;',
    symbol: '-',
    numeric: '&#45;',
    description: 'hyphen-minus',
    hex: 'u+002D ISOnum',
    cssIso: '\\002d',
    jsOctal: '\\55',
    category: 'special characters',
    like: false
  },
  {
    html: '&period;',
    symbol: '.',
    numeric: '&#46;',
    description: 'full stop; period',
    hex: 'u+002E ISOnum',
    cssIso: '\\002e',
    jsOctal: '\\56',
    category: 'special characters',
    like: false
  },
  {
    html: '&sol;',
    symbol: '/',
    numeric: '&#47;',
    description: 'solidus; slash',
    hex: 'u+002F ISOnum',
    cssIso: '\\002f',
    jsOctal: '\\57',
    category: 'special characters',
    like: false
  },
  {
    html: '&colon;',
    symbol: ':',
    numeric: '&#58;',
    description: 'colon',
    hex: 'u+003A ISOnum',
    cssIso: '\\003a',
    jsOctal: '\\72',
    category: 'special characters',
    like: false
  },
  {
    html: '&semi;',
    symbol: ';',
    numeric: '&#59;',
    description: 'semicolon',
    hex: 'u+003B ISOnum',
    cssIso: '\\003b',
    jsOctal: '\\73',
    category: 'special characters',
    like: false
  },
  {
    html: '&lt;',
    symbol: '<',
    numeric: '&#60;',
    description: 'less-than',
    hex: 'u+003C ISOnum',
    cssIso: '\\003c',
    jsOctal: '\\74',
    category: 'special characters',
    like: false
  },
  {
    html: '&equals;',
    symbol: '=',
    numeric: '&#61;',
    description: 'equals',
    hex: 'u+003D ISOnum',
    cssIso: '\\003d',
    jsOctal: '\\75',
    category: 'special characters',
    like: false
  },
  {
    html: '&gt;',
    symbol: '>',
    numeric: '&#62;',
    description: 'greater-than sign',
    hex: 'u+003E ISOnum',
    cssIso: '\\003e',
    jsOctal: '\\76',
    category: 'special characters',
    like: false
  },
  {
    html: '&quest;',
    symbol: '?',
    numeric: '&#63;',
    description: 'question mark',
    hex: 'u+003F ISOnum',
    cssIso: '\\003f',
    jsOctal: '\\77',
    category: 'special characters',
    like: false
  },
  {
    html: '&commat;',
    symbol: '@',
    numeric: '&#64;',
    description: 'at sign; commercial at',
    hex: 'u+0040 ISOnum',
    cssIso: '\\0040',
    jsOctal: '\\100',
    category: 'special characters',
    like: false
  },
  {
    html: '&lsqb;',
    symbol: '[',
    numeric: '  &#91;',
    description: 'left square bracket',
    hex: 'u+005B ISOnum',
    cssIso: '\\005b',
    jsOctal: '\\133',
    category: 'special characters',
    like: false
  },
  {
    html: '&bsol;',
    symbol: '\\',
    numeric: '&#92;',
    description: 'backslash',
    hex: 'u+005C ISOnum',
    cssIso: '\\005c',
    jsOctal: '\\134',
    category: 'special characters',
    like: false
  },
  {
    html: '&rsqb;',
    symbol: ']',
    numeric: '&#93;',
    description: 'right square bracket',
    hex: 'u+005D ISOnum',
    cssIso: '\\005d',
    jsOctal: '\\135',
    category: 'special characters',
    like: false
  },
  {
    html: '&Hat;',
    symbol: '^',
    numeric: '&#94;',
    description: 'circumflex accent',
    hex: 'u+005E ISOnum',
    cssIso: '\\005e',
    jsOctal: '\\136',
    category: 'special characters',
    like: false
  },
  {
    html: '&lowbar;',
    symbol: '_',
    numeric: '&#95;',
    description: 'low line',
    hex: 'u+005F ISOnum',
    cssIso: '\\005f',
    jsOctal: '\\137',
    category: 'special characters',
    like: false
  },
  {
    html: '&grave;',
    symbol: '`',
    numeric: '&#96;',
    description: 'grave accent',
    hex: 'u+0060 ISOnum',
    cssIso: '\\0060',
    jsOctal: '\\u0060',
    category: 'special characters',
    like: false
  },
  {
    html: '&lcub;',
    symbol: '{',
    numeric: '&#123;',
    description: 'left curly bracket',
    hex: 'u+007b ISOnum',
    cssIso: '\\007b',
    jsOctal: '\\173',
    category: 'special characters',
    like: false
  },
  {
    html: '&verbar;',
    symbol: '|',
    numeric: '&#124;',
    description: 'vertical bar',
    hex: 'u+007c ISOnum',
    cssIso: '\\007c',
    jsOctal: '\\174',
    category: 'special characters',
    like: false
  },
  {
    html: '&rcub;',
    symbol: '}',
    numeric: '&#125;',
    description: 'right curly bracket',
    hex: 'u+007d ISOnum',
    cssIso: '\\007d',
    jsOctal: '\\175',
    category: 'special characters',
    like: false
  },
  {
    html: '',
    symbol: '~',
    numeric: '&#125;',
    description: 'tilde',
    hex: 'u+007e ISOnum',
    cssIso: '\\007e',
    jsOctal: '\\176',
    category: 'special characters',
    like: false
  },
  {
    html: '&nbsp;',
    symbol: ' ',
    numeric: '&#160;',
    description: 'no-break space',
    hex: '%A0',
    cssIso: '\\00a0',
    jsOctal: '\\240',
    category: 'latin'
  },
  {
    html: '&iexcl;',
    symbol: '¡',
    numeric: '&#161;',
    description: 'inverted exclamation mark',
    hex: '%A1',
    cssIso: '\\00a1',
    jsOctal: '\\241',
    category: 'latin'
  },
  {
    html: '&cent;',
    symbol: '¢',
    numeric: '&#162;',
    description: 'cent sign',
    hex: '%A2',
    cssIso: '\\00a2',
    jsOctal: '\\242',
    category: 'latin'
  },
  {
    html: '&pound;',
    symbol: '£',
    numeric: '&#163;',
    description: 'pound sterling sign',
    hex: '%A3',
    cssIso: '\\00a3',
    jsOctal: '\\243',
    category: 'latin'
  },
  {
    html: '&curren;',
    symbol: '¤',
    numeric: '&#164;',
    description: 'general currency sign',
    hex: '%A4',
    cssIso: '\\00a4',
    jsOctal: '\\244',
    category: 'latin'
  },
  {
    html: '&yen;',
    symbol: '¥',
    numeric: '&#165;',
    description: 'yen sign',
    hex: '%A5',
    cssIso: '\\00a5',
    jsOctal: '\\245',
    category: 'latin'
  },
  {
    html: '&#x20B9;',
    symbol: '₹',
    numeric: '&#x20B9;',
    description: 'Indian Rupee (INR) sign',
    hex: 'U+20B9',
    cssIso: '\\20B9',
    jsOctal: '\\u20B9',
    category: 'latin'
  },
  {
    html: '&brvbar;',
    symbol: '¦',
    numeric: '&#166;',
    description: 'broken (vertical) bar',
    hex: '%A6',
    cssIso: '\\00a6',
    jsOctal: '\\246',
    category: 'latin'
  },
  {
    html: '&sect;',
    symbol: '§',
    numeric: '&#167;',
    description: 'section sign',
    hex: '%A7',
    cssIso: '\\00a7',
    jsOctal: '\\247',
    category: 'latin'
  },
  {
    html: '&uml;',
    symbol: '¨',
    numeric: '&#168;',
    description: 'umlaut (dieresis)',
    hex: '%A8',
    cssIso: '\\00a8',
    jsOctal: '\\250',
    category: 'latin'
  },
  {
    html: '&copy;',
    symbol: '©',
    numeric: '&#169;',
    description: 'copyright sign',
    hex: '%A9',
    cssIso: '\\00a9',
    jsOctal: '\\251',
    category: 'latin'
  },
  {
    html: '&ordf;',
    symbol: 'ª',
    numeric: '&#170;',
    description: 'ordinal indicator, feminine',
    hex: '%AA',
    cssIso: '\\00aa',
    jsOctal: '\\252',
    category: 'latin'
  },
  {
    html: '&laquo;',
    symbol: '«',
    numeric: '&#171;',
    description: 'angle quotation mark, left',
    hex: '%AB',
    cssIso: '\\00ab',
    jsOctal: '\\253',
    category: 'latin'
  },
  {
    html: '&not;',
    symbol: '¬',
    numeric: '&#172;',
    description: 'not sign',
    hex: '%AC',
    cssIso: '\\00ac',
    jsOctal: '\\254',
    category: 'latin'
  },
  {
    html: '&shy;',
    symbol: '',
    numeric: '&#173;',
    description: 'soft hyphen',
    hex: '%AD',
    cssIso: '\\00ad',
    jsOctal: '\\255',
    category: 'latin'
  },
  {
    html: '&reg;',
    symbol: '®',
    numeric: '&#174;',
    description: 'registered sign',
    hex: '%AE',
    cssIso: '\\00ae',
    jsOctal: '\\256',
    category: 'latin'
  },
  {
    html: '&macr;',
    symbol: '¯',
    numeric: '&#175;',
    description: 'macron',
    hex: '%AF',
    cssIso: '\\00af',
    jsOctal: '\\257',
    category: 'latin'
  },
  {
    html: '&deg;',
    symbol: '°',
    numeric: '&#176;',
    description: 'degree sign',
    hex: '%B0',
    cssIso: '\\00b0',
    jsOctal: '\\260',
    category: 'latin'
  },
  {
    html: '&plusmn;',
    symbol: '±',
    numeric: '&#177;',
    description: 'plus-or-minus sign',
    hex: '%B1',
    cssIso: '\\00b1',
    jsOctal: '\\261',
    category: 'latin'
  },
  {
    html: '&sup2;',
    symbol: '²',
    numeric: '&#178;',
    description: 'superscript two',
    hex: '%B2',
    cssIso: '\\00b2',
    jsOctal: '\\262',
    category: 'latin'
  },
  {
    html: '&sup3;',
    symbol: '³',
    numeric: '&#179;',
    description: 'superscript three',
    hex: '%B3',
    cssIso: '\\00b3',
    jsOctal: '\\263',
    category: 'latin'
  },
  {
    html: '&acute;',
    symbol: '´',
    numeric: '&#180;',
    description: 'acute accent',
    hex: '%B4',
    cssIso: '\\00b4',
    jsOctal: '\\264',
    category: 'latin'
  },
  {
    html: '&micro;',
    symbol: 'µ',
    numeric: '&#181;',
    description: 'micro sign',
    hex: '%B5',
    cssIso: '\\00b5',
    jsOctal: '\\265',
    category: 'latin'
  },
  {
    html: '&para;',
    symbol: '¶',
    numeric: '&#182;',
    description: 'pilcrow (paragraph sign)',
    hex: '%B6',
    cssIso: '\\00b6',
    jsOctal: '\\266',
    category: 'latin'
  },
  {
    html: '&middot;',
    symbol: '·',
    numeric: '&#183;',
    description: 'middle dot',
    hex: '%B7',
    cssIso: '\\00b7',
    jsOctal: '\\267',
    category: 'latin'
  },
  {
    html: '&cedil;',
    symbol: '¸',
    numeric: '&#184;',
    description: 'cedilla',
    hex: '%B8',
    cssIso: '\\00b8',
    jsOctal: '\\270',
    category: 'latin'
  },
  {
    html: '&sup1;',
    symbol: '¹',
    numeric: '&#185;',
    description: 'superscript one',
    hex: '%B9',
    cssIso: '\\00b9',
    jsOctal: '\\271',
    category: 'latin'
  },
  {
    html: '&ordm;',
    symbol: 'º',
    numeric: '&#186;',
    description: 'ordinal indicator, masculine',
    hex: '%BA',
    cssIso: '\\00ba',
    jsOctal: '\\272',
    category: 'latin'
  },
  {
    html: '&raquo;',
    symbol: '»',
    numeric: '&#187;',
    description: 'angle quotation mark, right',
    hex: '%BB',
    cssIso: '\\00bb',
    jsOctal: '\\273',
    category: 'latin'
  },
  {
    html: '&frac14;',
    symbol: '¼',
    numeric: '&#188;',
    description: 'fraction one-quarter',
    hex: '%BC',
    cssIso: '\\00bc',
    jsOctal: '\\274',
    category: 'latin'
  },
  {
    html: '&frac12;',
    symbol: '½',
    numeric: '&#189;',
    description: 'fraction one-half',
    hex: '%BD',
    cssIso: '\\00bd',
    jsOctal: '\\275',
    category: 'latin'
  },
  {
    html: '&frac34;',
    symbol: '¾',
    numeric: '&#190;',
    description: 'fraction three-quarters',
    hex: '%BE',
    cssIso: '\\00be',
    jsOctal: '\\276',
    category: 'latin'
  },
  {
    html: '&iquest;',
    symbol: '¿',
    numeric: '&#191;',
    description: 'inverted question mark',
    hex: '%BF',
    cssIso: '\\00bf',
    jsOctal: '\\277',
    category: 'latin'
  },
  {
    html: '&Agrave;',
    symbol: 'À',
    numeric: '&#192;',
    description: 'capital A, grave accent',
    hex: '%C0',
    cssIso: '\\00c0',
    jsOctal: '\\300',
    category: 'latin'
  },
  {
    html: '&Aacute;',
    symbol: 'Á',
    numeric: '&#193;',
    description: 'capital A, acute accent',
    hex: '%C1',
    cssIso: '\\00c1',
    jsOctal: '\\301',
    category: 'latin'
  },
  {
    html: '&Acirc;',
    symbol: 'Â',
    numeric: '&#194;',
    description: 'capital A, circumflex accent',
    hex: '%C2',
    cssIso: '\\00c2',
    jsOctal: '\\302',
    category: 'latin'
  },
  {
    html: '&Atilde;',
    symbol: 'Ã',
    numeric: '&#195;',
    description: 'capital A, tilde',
    hex: '%C3',
    cssIso: '\\00c3',
    jsOctal: '\\303',
    category: 'latin'
  },
  {
    html: '&Auml;',
    symbol: 'Ä',
    numeric: '&#196;',
    description: 'capital A, dieresis or umlaut mark',
    hex: '%C4',
    cssIso: '\\00c4',
    jsOctal: '\\304',
    category: 'latin'
  },
  {
    html: '&Aring;',
    symbol: 'Å',
    numeric: '&#197;',
    description: 'capital A, ring',
    hex: '%C5',
    cssIso: '\\00c5',
    jsOctal: '\\305',
    category: 'latin'
  },
  {
    html: '&AElig;',
    symbol: 'Æ',
    numeric: '&#198;',
    description: 'capital AE diphthong (ligature)',
    hex: '%C6',
    cssIso: '\\00c6',
    jsOctal: '\\306',
    category: 'latin'
  },
  {
    html: '&Ccedil;',
    symbol: 'Ç',
    numeric: '&#199;',
    description: 'capital C, cedilla',
    hex: '%C7',
    cssIso: '\\00c7',
    jsOctal: '\\307',
    category: 'latin'
  },
  {
    html: '&Egrave;',
    symbol: 'È',
    numeric: '&#200;',
    description: 'capital E, grave accent',
    hex: '%C8',
    cssIso: '\\00c8',
    jsOctal: '\\310',
    category: 'latin'
  },
  {
    html: '&Eacute;',
    symbol: 'É',
    numeric: '&#201;',
    description: 'capital E, acute accent',
    hex: '%C9',
    cssIso: '\\00c9',
    jsOctal: '\\311',
    category: 'latin'
  },
  {
    html: '&Ecirc;',
    symbol: 'Ê',
    numeric: '&#202;',
    description: 'capital E, circumflex accent',
    hex: '%CA',
    cssIso: '\\00ca',
    jsOctal: '\\312',
    category: 'latin'
  },
  {
    html: '&Euml;',
    symbol: 'Ë',
    numeric: '&#203;',
    description: 'capital E, dieresis or umlaut mark',
    hex: '%CB',
    cssIso: '\\00cb',
    jsOctal: '\\313',
    category: 'latin'
  },
  {
    html: '&Igrave;',
    symbol: 'Ì',
    numeric: '&#204;',
    description: 'capital I, grave accent',
    hex: '%CC',
    cssIso: '\\00cc',
    jsOctal: '\\314',
    category: 'latin'
  },
  {
    html: '&Iacute;',
    symbol: 'Í',
    numeric: '&#205;',
    description: 'capital I, acute accent',
    hex: '%CD',
    cssIso: '\\00cd',
    jsOctal: '\\315',
    category: 'latin'
  },
  {
    html: '&Icirc;',
    symbol: 'Î',
    numeric: '&#206;',
    description: 'capital I, circumflex accent',
    hex: '%CE',
    cssIso: '\\00ce',
    jsOctal: '\\316',
    category: 'latin'
  },
  {
    html: '&Iuml;',
    symbol: 'Ï',
    numeric: '&#207;',
    description: 'capital I, dieresis or umlaut mark',
    hex: '%CF',
    cssIso: '\\00cf',
    jsOctal: '\\317',
    category: 'latin'
  },
  {
    html: '&ETH;',
    symbol: 'Ð',
    numeric: '&#208;',
    description: 'capital Eth, Icelandic',
    hex: '%D0',
    cssIso: '\\00d0',
    jsOctal: '\\320',
    category: 'latin'
  },
  {
    html: '&Ntilde;',
    symbol: 'Ñ',
    numeric: '&#209;',
    description: 'capital N, tilde',
    hex: '%D1',
    cssIso: '\\00d1',
    jsOctal: '\\321',
    category: 'latin'
  },
  {
    html: '&Ograve;',
    symbol: 'Ò',
    numeric: '&#210;',
    description: 'capital O, grave accent',
    hex: '%D2',
    cssIso: '\\00d2',
    jsOctal: '\\322',
    category: 'latin'
  },
  {
    html: '&Oacute;',
    symbol: 'Ó',
    numeric: '&#211;',
    description: 'capital O, acute accent',
    hex: '%D3',
    cssIso: '\\00d3',
    jsOctal: '\\323',
    category: 'latin'
  },
  {
    html: '&Ocirc;',
    symbol: 'Ô',
    numeric: '&#212;',
    description: 'capital O, circumflex accent',
    hex: '%D4',
    cssIso: '\\00d4',
    jsOctal: '\\324',
    category: 'latin'
  },
  {
    html: '&Otilde;',
    symbol: 'Õ',
    numeric: '&#213;',
    description: 'capital O, tilde',
    hex: '%D5',
    cssIso: '\\00d5',
    jsOctal: '\\325',
    category: 'latin'
  },
  {
    html: '&Ouml;',
    symbol: 'Ö',
    numeric: '&#214;',
    description: 'capital O, dieresis or umlaut mark',
    hex: '%D6',
    cssIso: '\\00d6',
    jsOctal: '\\326',
    category: 'latin'
  },
  {
    html: '&times;',
    symbol: '×',
    numeric: '&#215;',
    description: 'multiply sign',
    hex: '%D7',
    cssIso: '\\00d7',
    jsOctal: '\\327',
    category: 'latin'
  },
  {
    html: '&Oslash;',
    symbol: 'Ø',
    numeric: '&#216;',
    description: 'capital O, slash',
    hex: '%D8',
    cssIso: '\\00d8',
    jsOctal: '\\330',
    category: 'latin'
  },
  {
    html: '&Ugrave;',
    symbol: 'Ù',
    numeric: '&#217;',
    description: 'capital U, grave accent',
    hex: '%D9',
    cssIso: '\\00d9',
    jsOctal: '\\331',
    category: 'latin'
  },
  {
    html: '&Uacute;',
    symbol: 'Ú',
    numeric: '&#218;',
    description: 'capital U, acute accent',
    hex: '%DA',
    cssIso: '\\00da',
    jsOctal: '\\332',
    category: 'latin'
  },
  {
    html: '&Ucirc;',
    symbol: 'Û',
    numeric: '&#219;',
    description: 'capital U, circumflex accent',
    hex: '%DB',
    cssIso: '\\00db',
    jsOctal: '\\333',
    category: 'latin'
  },
  {
    html: '&Uuml;',
    symbol: 'Ü',
    numeric: '&#220;',
    description: 'capital U, dieresis or umlaut mark',
    hex: '%DC',
    cssIso: '\\00dc',
    jsOctal: '\\334',
    category: 'latin'
  },
  {
    html: '&Yacute;',
    symbol: 'Ý',
    numeric: '&#221;',
    description: 'capital Y, acute accent',
    hex: '%DD',
    cssIso: '\\00dd',
    jsOctal: '\\335',
    category: 'latin'
  },
  {
    html: '&THORN;',
    symbol: 'Þ',
    numeric: '&#222;',
    description: 'capital THORN, Icelandic',
    hex: '%DE',
    cssIso: '\\00de',
    jsOctal: '\\336',
    category: 'latin'
  },
  {
    html: '&szlig;',
    symbol: 'ß',
    numeric: '&#223;',
    description: 'small sharp s, German (sz ligature)',
    hex: '%DF',
    cssIso: '\\00df',
    jsOctal: '\\337',
    category: 'latin'
  },
  {
    html: '&agrave;',
    symbol: 'à',
    numeric: '&#224;',
    description: 'small a, grave accent',
    hex: '%E0',
    cssIso: '\\00e0',
    jsOctal: '\\340',
    category: 'latin'
  },
  {
    html: '&aacute;',
    symbol: 'á',
    numeric: '&#225;',
    description: 'small a, acute accent',
    hex: '%E1',
    cssIso: '\\00e1',
    jsOctal: '\\341',
    category: 'latin'
  },
  {
    html: '&acirc;',
    symbol: 'â',
    numeric: '&#226;',
    description: 'small a, circumflex accent',
    hex: '%E2',
    cssIso: '\\00e2',
    jsOctal: '\\342',
    category: 'latin'
  },
  {
    html: '&atilde;',
    symbol: 'ã',
    numeric: '&#227;',
    description: 'small a, tilde',
    hex: '%E3',
    cssIso: '\\00e3',
    jsOctal: '\\343',
    category: 'latin'
  },
  {
    html: '&auml;',
    symbol: 'ä',
    numeric: '&#228;',
    description: 'small a, dieresis or umlaut mark',
    hex: '%E4',
    cssIso: '\\00e4',
    jsOctal: '\\344',
    category: 'latin'
  },
  {
    html: '&aring;',
    symbol: 'å',
    numeric: '&#229;',
    description: 'small a, ring',
    hex: '%E5',
    cssIso: '\\00e5',
    jsOctal: '\\345',
    category: 'latin'
  },
  {
    html: '&aelig;',
    symbol: 'æ',
    numeric: '&#230;',
    description: 'small ae diphthong (ligature)',
    hex: '%E6',
    cssIso: '\\00e6',
    jsOctal: '\\346',
    category: 'latin'
  },
  {
    html: '&ccedil;',
    symbol: 'ç',
    numeric: '&#231;',
    description: 'small c, cedilla',
    hex: '%E7',
    cssIso: '\\00e7',
    jsOctal: '\\347',
    category: 'latin'
  },
  {
    html: '&egrave;',
    symbol: 'è',
    numeric: '&#232;',
    description: 'small e, grave accent',
    hex: '%E8',
    cssIso: '\\00e8',
    jsOctal: '\\350',
    category: 'latin'
  },
  {
    html: '&eacute;',
    symbol: 'é',
    numeric: '&#233;',
    description: 'small e, acute accent',
    hex: '%E9',
    cssIso: '\\00e9',
    jsOctal: '\\351',
    category: 'latin'
  },
  {
    html: '&ecirc;',
    symbol: 'ê',
    numeric: '&#234;',
    description: 'small e, circumflex accent',
    hex: '%EA',
    cssIso: '\\00ea',
    jsOctal: '\\352',
    category: 'latin'
  },
  {
    html: '&euml;',
    symbol: 'ë',
    numeric: '&#235;',
    description: 'small e, dieresis or umlaut mark',
    hex: '%EB',
    cssIso: '\\00eb',
    jsOctal: '\\353',
    category: 'latin'
  },
  {
    html: '&igrave;',
    symbol: 'ì',
    numeric: '&#236;',
    description: 'small i, grave accent',
    hex: '%EC',
    cssIso: '\\00ec',
    jsOctal: '\\354',
    category: 'latin'
  },
  {
    html: '&iacute;',
    symbol: 'í',
    numeric: '&#237;',
    description: 'small i, acute accent',
    hex: '%ED',
    cssIso: '\\00ed',
    jsOctal: '\\355',
    category: 'latin'
  },
  {
    html: '&icirc;',
    symbol: 'î',
    numeric: '&#238;',
    description: 'small i, circumflex accent',
    hex: '%EE',
    cssIso: '\\00ee',
    jsOctal: '\\356',
    category: 'latin'
  },
  {
    html: '&iuml;',
    symbol: 'ï',
    numeric: '&#239;',
    description: 'small i, dieresis or umlaut mark',
    hex: '%EF',
    cssIso: '\\00ef',
    jsOctal: '\\357',
    category: 'latin'
  },
  {
    html: '&eth;',
    symbol: 'ð',
    numeric: '&#240;',
    description: 'small eth, Icelandic',
    hex: '%F0',
    cssIso: '\\00f0',
    jsOctal: '\\360',
    category: 'latin'
  },
  {
    html: '&ntilde;',
    symbol: 'ñ',
    numeric: '&#241;',
    description: 'small n, tilde',
    hex: '%F1',
    cssIso: '\\00f1',
    jsOctal: '\\361',
    category: 'latin'
  },
  {
    html: '&ograve;',
    symbol: 'ò',
    numeric: '&#242;',
    description: 'small o, grave accent',
    hex: '%F2',
    cssIso: '\\00f2',
    jsOctal: '\\362',
    category: 'latin'
  },
  {
    html: '&oacute;',
    symbol: 'ó',
    numeric: '&#243;',
    description: 'small o, acute accent',
    hex: '%F3',
    cssIso: '\\00f3',
    jsOctal: '\\363',
    category: 'latin'
  },
  {
    html: '&ocirc;',
    symbol: 'ô',
    numeric: '&#244;',
    description: 'small o, circumflex accent',
    hex: '%F4',
    cssIso: '\\00f4',
    jsOctal: '\\364',
    category: 'latin'
  },
  {
    html: '&otilde;',
    symbol: 'õ',
    numeric: '&#245;',
    description: 'small o, tilde',
    hex: '%F5',
    cssIso: '\\00f5',
    jsOctal: '\\365',
    category: 'latin'
  },
  {
    html: '&ouml;',
    symbol: 'ö',
    numeric: '&#246;',
    description: 'small o, dieresis or umlaut mark',
    hex: '%F6',
    cssIso: '\\00f6',
    jsOctal: '\\366',
    category: 'latin'
  },
  {
    html: '&divide;',
    symbol: '÷',
    numeric: '&#247;',
    description: 'divide sign',
    hex: '%F7',
    cssIso: '\\00f7',
    jsOctal: '\\367',
    category: 'latin'
  },
  {
    html: '&oslash;',
    symbol: 'ø',
    numeric: '&#248;',
    description: 'small o, slash',
    hex: '%F8',
    cssIso: '\\00f8',
    jsOctal: '\\370',
    category: 'latin'
  },
  {
    html: '&ugrave;',
    symbol: 'ù',
    numeric: '&#249;',
    description: 'small u, grave accent',
    hex: '%F9',
    cssIso: '\\00f9',
    jsOctal: '\\371',
    category: 'latin'
  },
  {
    html: '&uacute;',
    symbol: 'ú',
    numeric: '&#250;',
    description: 'small u, acute accent',
    hex: '%FA',
    cssIso: '\\00fa',
    jsOctal: '\\372',
    category: 'latin'
  },
  {
    html: '&ucirc;',
    symbol: 'û',
    numeric: '&#251;',
    description: 'small u, circumflex accent',
    hex: '%FB',
    cssIso: '\\00fb',
    jsOctal: '\\373',
    category: 'latin'
  },
  {
    html: '&uuml;',
    symbol: 'ü',
    numeric: '&#252;',
    description: 'small u, dieresis or umlaut mark',
    hex: '%FC',
    cssIso: '\\00fc',
    jsOctal: '\\374',
    category: 'latin'
  },
  {
    html: '&yacute;',
    symbol: 'ý',
    numeric: '&#253;',
    description: 'small y, acute accent',
    hex: '%FD',
    cssIso: '\\00fd',
    jsOctal: '\\375',
    category: 'latin'
  },
  {
    html: '&thorn;',
    symbol: 'þ',
    numeric: '&#254;',
    description: 'small thorn, Icelandic',
    hex: '%FE',
    cssIso: '\\00fe',
    jsOctal: '\\376',
    category: 'latin'
  },
  {
    html: '&yuml;',
    symbol: 'ÿ',
    numeric: '&#255;',
    description: 'small y, dieresis or umlaut mark',
    hex: '%FF',
    cssIso: '\\00ff',
    jsOctal: '\\377',
    category: 'latin'
  },
  {
    html: '&OElig;',
    symbol: 'Œ',
    numeric: '&#338;',
    description: 'latin capital ligature oe',
    hex: 'u+0152 ISOlat2',
    cssIso: '\\0152',
    jsOctal: '\\u0152',
    category: 'latin extended'
  },
  {
    html: '&oelig;',
    symbol: 'œ',
    numeric: '&#339;',
    description: 'latin small ligature oe',
    hex: 'u+0153 ISOlat2',
    cssIso: '\\0153',
    jsOctal: '\\u0153',
    category: 'latin extended'
  },
  {
    html: '&Scaron;',
    symbol: 'Š',
    numeric: '&#352;',
    description: 'latin capital letter s with caron',
    hex: 'u+0160 ISOlat2',
    cssIso: '\\0160',
    jsOctal: '\\u0160',
    category: 'latin extended'
  },
  {
    html: '&scaron;',
    symbol: 'š',
    numeric: '&#353;',
    description: 'latin small letter s with caron',
    hex: 'u+0161 ISOlat2',
    cssIso: '\\0161',
    jsOctal: '\\u0161',
    category: 'latin extended'
  },
  {
    html: '&Yuml;',
    symbol: 'Ÿ',
    numeric: '&#376;',
    description: 'latin capital letter y with diaeresis',
    hex: 'u+0178 ISOlat2',
    cssIso: '\\0178',
    jsOctal: '\\u0178',
    category: 'latin extended'
  },
  {
    html: '&fnof;',
    symbol: 'ƒ',
    numeric: '&#402;',
    description: 'latin small f with hook',
    hex: 'u+0192 ISOtech',
    cssIso: '\\0192',
    jsOctal: '\\u0192',
    category: 'latin extended'
  },
  {
    html: '&circ;',
    symbol: 'ˆ',
    numeric: '',
    description: 'modifier letter circumflex accent',
    hex: 'u+02C6 ISOpub',
    cssIso: '\\02c6',
    jsOctal: '\\u02c6',
    category: 'spacing modifier letters'
  },
  {
    html: '&tilde;',
    symbol: '˜',
    numeric: '',
    description: 'small tilde',
    hex: 'u+02DC ISOdia',
    cssIso: '\\02dc',
    jsOctal: '\\u02dc',
    category: 'spacing modifier letters'
  },
  {
    html: '&Alpha;',
    symbol: 'Α',
    numeric: '&#913;',
    description: 'greek capital letter alpha',
    hex: 'u+0391',
    cssIso: '\\0391',
    jsOctal: '\\u0391',
    category: 'greek'
  },
  {
    html: '&Beta;',
    symbol: 'Β',
    numeric: '&#914;',
    description: 'greek capital letter beta',
    hex: 'u+0392',
    cssIso: '\\0392',
    jsOctal: '\\u0392',
    category: 'greek'
  },
  {
    html: '&Gamma;',
    symbol: 'Γ',
    numeric: '&#915;',
    description: 'greek capital letter gamma',
    hex: 'u+0393 ISOgrk3',
    cssIso: '\\0393',
    jsOctal: '\\u0395',
    category: 'greek'
  },
  {
    html: '&Delta;',
    symbol: 'Δ',
    numeric: '&#916;',
    description: 'greek capital letter delta',
    hex: 'u+0394 ISOgrk3',
    cssIso: '\\0394',
    jsOctal: '\\u0394',
    category: 'greek'
  },
  {
    html: '&Epsilon;',
    symbol: 'Ε',
    numeric: '&#917;',
    description: 'greek capital letter epsilon',
    hex: 'u+0395',
    cssIso: '\\0395',
    jsOctal: '\\u0395',
    category: 'greek'
  },
  {
    html: '&Zeta;',
    symbol: 'Ζ',
    numeric: '&#918;',
    description: 'greek capital letter zeta',
    hex: 'u+0396',
    cssIso: '\\0396',
    jsOctal: '\\u0396',
    category: 'greek'
  },
  {
    html: '&Eta;',
    symbol: 'Η',
    numeric: '&#919;',
    description: 'greek capital letter eta',
    hex: 'u+0397',
    cssIso: '\\0397',
    jsOctal: '\\u0397',
    category: 'greek'
  },
  {
    html: '&Theta;',
    symbol: 'Θ',
    numeric: '&#920;',
    description: 'greek capital letter theta',
    hex: 'u+0398 ISOgrk3',
    cssIso: '\\0398',
    jsOctal: '\\u0398',
    category: 'greek'
  },
  {
    html: '&Iota;',
    symbol: 'Ι',
    numeric: '&#921;',
    description: 'greek capital letter iota',
    hex: 'u+0399',
    cssIso: '\\0399',
    jsOctal: '\\u0399',
    category: 'greek'
  },
  {
    html: '&Kappa;',
    symbol: 'Κ',
    numeric: '&#922;',
    description: 'greek capital letter kappa',
    hex: 'u+039A',
    cssIso: '\\039a',
    jsOctal: '\\u039a',
    category: 'greek'
  },
  {
    html: '&Lambda;',
    symbol: 'Λ',
    numeric: '&#923;',
    description: 'greek capital letter lambda',
    hex: 'u+039B ISOgrk3',
    cssIso: '\\039b',
    jsOctal: '\\u039b',
    category: 'greek'
  },
  {
    html: '&Mu;',
    symbol: 'Μ',
    numeric: '&#924;',
    description: 'greek capital letter mu',
    hex: 'u+039C',
    cssIso: '\\039c',
    jsOctal: '\\u039c',
    category: 'greek'
  },
  {
    html: '&Nu;',
    symbol: 'Ν',
    numeric: '&#925;',
    description: 'greek capital letter nu',
    hex: 'u+039D',
    cssIso: '\\039d',
    jsOctal: '\\u039D',
    category: 'greek'
  },
  {
    html: '&Xi;',
    symbol: 'Ξ',
    numeric: '&#926;',
    description: 'greek capital letter xi',
    hex: 'u+039E ISOgrk3',
    cssIso: '\\039e',
    jsOctal: '\\u039e',
    category: 'greek'
  },
  {
    html: '&Omicron;',
    symbol: 'Ο',
    numeric: '&#927;',
    description: 'greek capital letter omicron',
    hex: 'u+039F',
    cssIso: '\\039f',
    jsOctal: '\\u039f',
    category: 'greek'
  },
  {
    html: '&Pi;',
    symbol: 'Π',
    numeric: '&#928;',
    description: 'greek capital letter pi',
    hex: 'u+03A0 ISOgrk3',
    cssIso: '\\03a0',
    jsOctal: '\\u03a0',
    category: 'greek'
  },
  {
    html: '&Rho;',
    symbol: 'Ρ',
    numeric: '&#929;',
    description: 'greek capital letter rho',
    hex: 'u+03A1',
    cssIso: '\\03a1',
    jsOctal: '\\u03a1',
    category: 'greek'
  },
  {
    html: '&Sigma;',
    symbol: 'Σ',
    numeric: '&#931;',
    description: 'greek capital letter sigma',
    hex: 'u+03A3 ISOgrk3',
    cssIso: '\\03a3',
    jsOctal: '\\u03A3',
    category: 'greek'
  },
  {
    html: '&Tau;',
    symbol: 'Τ',
    numeric: '&#932;',
    description: 'greek capital letter tau',
    hex: 'u+03A4',
    cssIso: '\\03a4',
    jsOctal: '\\u03A4',
    category: 'greek'
  },
  {
    html: '&Upsilon;',
    symbol: 'Υ',
    numeric: '&#933;',
    description: 'greek capital letter upsilon',
    hex: 'u+03A5 ISOgrk3',
    cssIso: '\\03a5',
    jsOctal: '\\u03A5',
    category: 'greek'
  },
  {
    html: '&Phi;',
    symbol: 'Φ',
    numeric: '&#934;',
    description: 'greek capital letter phi',
    hex: 'u+03A6 ISOgrk3',
    cssIso: '\\03a6',
    jsOctal: '\\u03A6',
    category: 'greek'
  },
  {
    html: '&Chi;',
    symbol: 'Χ',
    numeric: '&#935;',
    description: 'greek capital letter chi',
    hex: 'u+03A7',
    cssIso: '\\03a7',
    jsOctal: '\\u03A7',
    category: 'greek'
  },
  {
    html: '&Psi;',
    symbol: 'Ψ',
    numeric: '&#936;',
    description: 'greek capital letter psi',
    hex: 'u+03A8 ISOgrk3',
    cssIso: '\\03a8',
    jsOctal: '\\u03A8',
    category: 'greek'
  },
  {
    html: '&Omega;',
    symbol: 'Ω',
    numeric: '&#937;',
    description: 'greek capital letter omega',
    hex: 'u+03A9 ISOgrk3',
    cssIso: '\\03a9',
    jsOctal: '\\u03A9',
    category: 'greek'
  },
  {
    html: '&alpha;',
    symbol: 'α',
    numeric: '&#945;',
    description: 'greek small letter alpha',
    hex: 'u+03B1 ISOgrk3',
    cssIso: '\\03b1',
    jsOctal: '\\u03b1',
    category: 'greek'
  },
  {
    html: '&beta;',
    symbol: 'β',
    numeric: '&#946;',
    description: 'greek small letter beta',
    hex: 'u+03B2 ISOgrk3',
    cssIso: '\\03b2',
    jsOctal: '\\u03b2',
    category: 'greek'
  },
  {
    html: '&gamma;',
    symbol: 'γ',
    numeric: '&#947;',
    description: 'greek small letter gamma',
    hex: 'u+03B3 ISOgrk3',
    cssIso: '\\03b3',
    jsOctal: '\\u03b3',
    category: 'greek'
  },
  {
    html: '&delta;',
    symbol: 'δ',
    numeric: '&#948;',
    description: 'greek small letter delta',
    hex: 'u+03B4 ISOgrk3',
    cssIso: '\\03b4',
    jsOctal: '\\u03b4',
    category: 'greek'
  },
  {
    html: '&epsilon;',
    symbol: 'ε',
    numeric: '&#949;',
    description: 'greek small letter epsilon',
    hex: 'u+03B5 ISOgrk3',
    cssIso: '\\03b5',
    jsOctal: '\\u03b5',
    category: 'greek'
  },
  {
    html: '&zeta;',
    symbol: 'ζ',
    numeric: '&#950;',
    description: 'greek small letter zeta',
    hex: 'u+03B6 ISOgrk3',
    cssIso: '\\03b6',
    jsOctal: '\\u03b6',
    category: 'greek'
  },
  {
    html: '&eta;',
    symbol: 'η',
    numeric: '&#951;',
    description: 'greek small letter eta',
    hex: 'u+03B7 ISOgrk3',
    cssIso: '\\03b7',
    jsOctal: '\\u03b7',
    category: 'greek'
  },
  {
    html: '&theta;',
    symbol: 'θ',
    numeric: '&#952;',
    description: 'greek small letter theta',
    hex: 'u+03B8 ISOgrk3',
    cssIso: '\\03b8',
    jsOctal: '\\u03b8',
    category: 'greek'
  },
  {
    html: '&iota;',
    symbol: 'ι',
    numeric: '&#953;',
    description: 'greek small letter iota',
    hex: 'u+03B9 ISOgrk3',
    cssIso: '\\03b9',
    jsOctal: '\\u03b9',
    category: 'greek'
  },
  {
    html: '&kappa;',
    symbol: 'κ',
    numeric: '&#954;',
    description: 'greek small letter kappa',
    hex: 'u+03BA ISOgrk3',
    cssIso: '\\03ba',
    jsOctal: '\\u03ba',
    category: 'greek'
  },
  {
    html: '&lambda;',
    symbol: 'λ',
    numeric: '&#955;',
    description: 'greek small letter lambda',
    hex: 'u+03BB ISOgrk3',
    cssIso: '\\03bb',
    jsOctal: '\\u03bb',
    category: 'greek'
  },
  {
    html: '&mu;',
    symbol: 'μ',
    numeric: '&#956;',
    description: 'greek small letter mu',
    hex: 'u+03BC ISOgrk3',
    cssIso: '\\03bc',
    jsOctal: '\\u03bc',
    category: 'greek'
  },
  {
    html: '&nu;',
    symbol: 'ν',
    numeric: '&#957;',
    description: 'greek small letter nu',
    hex: 'u+03BD ISOgrk3',
    cssIso: '\\03bd',
    jsOctal: '\\u03bd',
    category: 'greek'
  },
  {
    html: '&xi;',
    symbol: 'ξ',
    numeric: '&#958;',
    description: 'greek small letter xi',
    hex: 'u+03BE ISOgrk3',
    cssIso: '\\03be',
    jsOctal: '\\u03be',
    category: 'greek'
  },
  {
    html: '&omicron;',
    symbol: 'ο',
    numeric: '&#959;',
    description: 'greek small letter omicron',
    hex: 'u+03BF NEW',
    cssIso: '\\03bf',
    jsOctal: '\\u03bf',
    category: 'greek'
  },
  {
    html: '&pi;',
    symbol: 'π',
    numeric: '&#960;',
    description: 'greek small letter pi',
    hex: 'u+03C0 ISOgrk3',
    cssIso: '\\03c0',
    jsOctal: '\\u03c0',
    category: 'greek'
  },
  {
    html: '&rho;',
    symbol: 'ρ',
    numeric: '&#961;',
    description: 'greek small letter rho',
    hex: 'u+03C1 ISOgrk3',
    cssIso: '\\03c1',
    jsOctal: '\\u03c1',
    category: 'greek'
  },
  {
    html: '&sigmaf;',
    symbol: 'ς',
    numeric: '&#962;',
    description: 'greek small letter final sigma',
    hex: 'u+03C2 ISOgrk3',
    cssIso: '\\03C2',
    jsOctal: '\\u03c2',
    category: 'greek'
  },
  {
    html: '&sigma;',
    symbol: 'σ',
    numeric: '&#963;',
    description: 'greek small letter sigma',
    hex: 'u+03C3 ISOgrk3',
    cssIso: '\\03C3',
    jsOctal: '\\u03c3',
    category: 'greek'
  },
  {
    html: '&tau;',
    symbol: 'τ',
    numeric: '&#964;',
    description: 'greek small letter tau',
    hex: 'u+03C4 ISOgrk3',
    cssIso: '\\03C4',
    jsOctal: '\\u03c4',
    category: 'greek'
  },
  {
    html: '&upsilon;',
    symbol: 'υ',
    numeric: '&#965;',
    description: 'greek small letter upsilon',
    hex: 'u+03C5 ISOgrk3',
    cssIso: '\\03C5',
    jsOctal: '\\u03c5',
    category: 'greek'
  },
  {
    html: '&phi;',
    symbol: 'φ',
    numeric: '&#966;',
    description: 'greek small letter phi',
    hex: 'u+03C6 ISOgrk3',
    cssIso: '\\03C6',
    jsOctal: '\\03c6',
    category: 'greek'
  },
  {
    html: '&chi;',
    symbol: 'χ',
    numeric: '&#967;',
    description: 'greek small letter chi',
    hex: 'u+03C7 ISOgrk3',
    cssIso: '\\03C7',
    jsOctal: '\\u03c7',
    category: 'greek'
  },
  {
    html: '&psi;',
    symbol: 'ψ',
    numeric: '&#968;',
    description: 'greek small letter psi',
    hex: 'u+03C8 ISOgrk3',
    cssIso: '\\03C8',
    jsOctal: '\\u03c8',
    category: 'greek'
  },
  {
    html: '&omega;',
    symbol: 'ω',
    numeric: '&#969;',
    description: 'greek small letter omega',
    hex: 'u+03C9 ISOgrk3',
    cssIso: '\\03C9',
    jsOctal: '\\u03c9',
    category: 'greek'
  },
  {
    html: '&thetasym;',
    symbol: 'ϑ',
    numeric: '&#977;',
    description: 'greek small letter theta symbol',
    hex: 'u+03D1 NEW',
    cssIso: '\\03D1',
    jsOctal: '\\u03D1',
    category: 'greek'
  },
  {
    html: '&upsih;',
    symbol: 'ϒ',
    numeric: '&#978;',
    description: 'greek upsilon with hook symbol',
    hex: 'u+03D2 NEW',
    cssIso: '\\03D2',
    jsOctal: '\\u03D2',
    category: 'greek'
  },
  {
    html: '&piv;',
    symbol: 'ϖ',
    numeric: '&#982;',
    description: 'greek pi symbol',
    hex: 'u+03D6 ISOgrk3',
    cssIso: '\\03D6',
    jsOctal: '\\u03D6',
    category: 'greek'
  },
  {
    html: '&ensp;',
    symbol: '',
    numeric: '&#8194;',
    description: 'en space',
    hex: 'u+2002 ISOpub',
    cssIso: '\\2002',
    jsOctal: '\\u2002',
    category: 'punctuation'
  },
  {
    html: '&emsp;',
    symbol: '',
    numeric: '&#8195;',
    description: 'em space',
    hex: 'u+2003 ISOpub',
    cssIso: '\\2003',
    jsOctal: '\\u2003',
    category: 'punctuation'
  },
  {
    html: '&thinsp;',
    symbol: '',
    numeric: '&#8201;',
    description: 'thin space',
    hex: 'u+2009 ISOpub',
    cssIso: '\\2009',
    jsOctal: '\\u2009',
    category: 'punctuation'
  },
  {
    html: '&zwnj;',
    symbol: '',
    numeric: '&#8204;',
    description: 'zero width non-joiner',
    hex: 'u+200C NEW RFC 2070',
    cssIso: '\\200C',
    jsOctal: '\\u200C',
    category: 'punctuation'
  },
  {
    html: '&zwj;',
    symbol: '',
    numeric: '&#8205;',
    description: 'zero width joiner',
    hex: 'u+200D NEW RFC 2070',
    cssIso: '\\200D',
    jsOctal: '\\u200d',
    category: 'punctuation'
  },
  {
    html: '&lrm;',
    symbol: '',
    numeric: '&#8206;',
    description: 'left-to-right mark',
    hex: 'u+200E NEW RFC 2070',
    cssIso: '\\200E',
    jsOctal: '\\u200e',
    category: 'punctuation'
  },
  {
    html: '&rlm;',
    symbol: '',
    numeric: '&#8207;',
    description: 'right-to-left mark',
    hex: 'u+200F NEW RFC 2070',
    cssIso: '\\200F',
    jsOctal: '\\u200f',
    category: 'punctuation'
  },
  {
    html: '&ndash;',
    symbol: '–',
    numeric: '&#8211;',
    description: 'en dash',
    hex: 'u+2013 ISOpub',
    cssIso: '\\2013',
    jsOctal: '\\u2013',
    category: 'punctuation'
  },
  {
    html: '&mdash;',
    symbol: '—',
    numeric: '&#8212;',
    description: 'em dash',
    hex: 'u+2014 ISOpub',
    cssIso: '\\2014',
    jsOctal: '\\u2014',
    category: 'punctuation'
  },
  {
    html: '&lsquo;',
    symbol: '‘',
    numeric: '&#8216;',
    description: 'left single quotation mark',
    hex: 'u+2018 ISOnum',
    cssIso: '\\2018',
    jsOctal: '\\u2018',
    category: 'punctuation'
  },
  {
    html: '&rsquo;',
    symbol: '’',
    numeric: '&#8217;',
    description: 'right single quotation mark',
    hex: 'u+2019 ISOnum',
    cssIso: '\\2019',
    jsOctal: '\\u2019',
    category: 'punctuation'
  },
  {
    html: '&sbquo;',
    symbol: '‚',
    numeric: '&#8218;',
    description: 'single low-9 quotation mark',
    hex: 'u+201A NEW',
    cssIso: '\\201A',
    jsOctal: '\\u201a',
    category: 'punctuation'
  },
  {
    html: '&ldquo;',
    symbol: '“',
    numeric: '&#8220;',
    description: 'left double quotation mark',
    hex: 'u+201C ISOnum',
    cssIso: '\\201C',
    jsOctal: '\\u201c',
    category: 'punctuation'
  },
  {
    html: '&rdquo;',
    symbol: '”',
    numeric: '&#8221;',
    description: 'right double quotation mark',
    hex: 'u+201D ISOnum',
    cssIso: '\\201D',
    jsOctal: '\\u201d',
    category: 'punctuation'
  },
  {
    html: '&bdquo;',
    symbol: '„',
    numeric: '&#8222;',
    description: 'double low-9 quotation mark',
    hex: 'u+201E NEW',
    cssIso: '\\201E',
    jsOctal: '\\u201e',
    category: 'punctuation'
  },
  {
    html: '&dagger;',
    symbol: '†',
    numeric: '&#8224;',
    description: 'dagger',
    hex: 'u+2020 ISOpub',
    cssIso: '\\2020',
    jsOctal: '\\u2020',
    category: 'punctuation'
  },
  {
    html: '&Dagger;',
    symbol: '‡',
    numeric: '&#8225;',
    description: 'double dagger',
    hex: 'u+2021 ISOpub',
    cssIso: '\\2021',
    jsOctal: '\\u2021',
    category: 'punctuation'
  },
  {
    html: '&permil;',
    symbol: '‰',
    numeric: '&#8240;',
    description: 'per mille sign',
    hex: 'u+2030 ISOtech',
    cssIso: '\\2030',
    jsOctal: '\\u2030',
    category: 'punctuation'
  },
  {
    html: '&lsaquo;',
    symbol: '‹',
    numeric: '&#8249;',
    description: 'single left-pointing angle quotation mark',
    hex: 'u+2039 ISO proposed',
    cssIso: '\\2039',
    jsOctal: '\\u2039',
    category: 'punctuation'
  },
  {
    html: '&rsaquo;',
    symbol: '›',
    numeric: '&#8250;',
    description: 'single right-pointing angle quotation mark',
    hex: 'u+203A ISO proposed',
    cssIso: '\\203A',
    jsOctal: '\\u203a',
    category: 'punctuation'
  },
  {
    html: '&bull;',
    symbol: '•',
    numeric: '&#8226;',
    description: 'bullet, a.k.a. black small circle bullet is NOT the same as bullet operator — u+2219',
    hex: 'u+2022 ISOpub',
    cssIso: '\\2022',
    jsOctal: '\\u2219',
    category: 'punctuation'
  },
  {
    html: '&hellip;',
    symbol: '…',
    numeric: '&#8230;',
    description: 'horizontal ellipsis, a.k.a. three dot leader',
    hex: 'u+2026 ISOpub',
    cssIso: '\\2026',
    jsOctal: '\\u2026',
    category: 'punctuation'
  },
  {
    html: '&prime;',
    symbol: '′',
    numeric: '&#8242;',
    description: 'prime, a.k.a. minutes, a.k.a. feet',
    hex: 'u+2032 ISOtech',
    cssIso: '\\2032',
    jsOctal: '\\u2032',
    category: 'punctuation'
  },
  {
    html: '&Prime;',
    symbol: '″',
    numeric: '&#8243;',
    description: 'double prime, a.k.a. seconds, a.k.a. inches',
    hex: 'u+2033 ISOtech',
    cssIso: '\\2033',
    jsOctal: '\\u2033',
    category: 'punctuation'
  },
  {
    html: '&oline;',
    symbol: '‾',
    numeric: '&#8254;',
    description: 'overline, a.k.a. spacing overscore',
    hex: 'u+203E NEW',
    cssIso: '\\203E',
    jsOctal: '\\u203e',
    category: 'punctuation'
  },
  {
    html: '&frasl;',
    symbol: '⁄',
    numeric: '&#8260;',
    description: 'fraction slash',
    hex: 'u+2044 NEW',
    cssIso: '\\2044',
    jsOctal: '\\u8260',
    category: 'punctuation'
  },
  {
    html: '&weierp;',
    symbol: '℘',
    numeric: '&#8472;',
    description: 'script capital P, a.k.a. power set, a.k.a. Weierstrass p',
    hex: 'u+2118 ISOamso',
    cssIso: '\\2118',
    jsOctal: '\\u2118',
    category: 'letter-like symbols'
  },
  {
    html: '&image;',
    symbol: 'ℑ',
    numeric: '&#8465;',
    description: 'blackletter capital I, a.k.a. imaginary part',
    hex: 'u+2111 ISOamso',
    cssIso: '\\2111',
    jsOctal: '\\u2111',
    category: 'letter-like symbols'
  },
  {
    html: '&real;',
    symbol: 'ℜ',
    numeric: '&#8476;',
    description: 'blackletter capital R, a.k.a. real part symbol',
    hex: 'u+211C ISOamso',
    cssIso: '\\211C',
    jsOctal: '\\u211c',
    category: 'letter-like symbols'
  },
  {
    html: '&trade;',
    symbol: '™',
    numeric: '&#8482;',
    description: 'trade mark sign',
    hex: 'u+2122 ISOnum',
    cssIso: '\\2122',
    jsOctal: '\\u2122',
    category: 'letter-like symbols'
  },
  {
    html: '&alefsym;',
    symbol: 'ℵ',
    numeric: '&#8501;',
    description: 'alef symbol',
    hex: 'u+2135 NEW',
    cssIso: '\\2135',
    jsOctal: '\\u',
    category: 'letter-like symbols'
  },
  {
    html: '&larr;',
    symbol: '←',
    numeric: '&#8592;',
    description: 'leftwards arrow',
    hex: 'u+2190 ISOnum',
    cssIso: '\\2190',
    jsOctal: '\\u2190',
    category: 'arrows'
  },
  {
    html: '&uarr;',
    symbol: '↑',
    numeric: '&#8593;',
    description: 'upwards arrow',
    hex: 'u+2191 ISOnum',
    cssIso: '\\2191',
    jsOctal: '\\u2191',
    category: 'arrows'
  },
  {
    html: '&rarr;',
    symbol: '→',
    numeric: '&#8594;',
    description: 'rightwards arrow',
    hex: 'u+2192 ISOnum',
    cssIso: '\\2192',
    jsOctal: '\\u2192',
    category: 'arrows'
  },
  {
    html: '&darr;',
    symbol: '↓',
    numeric: '&#8595;',
    description: 'downwards arrow',
    hex: 'u+2193 ISOnum',
    cssIso: '\\2193',
    jsOctal: '\\u2193',
    category: 'arrows'
  },
  {
    html: '&harr;',
    symbol: '↔',
    numeric: '&#8596;',
    description: 'left right arrow',
    hex: 'u+2194 ISOamsa',
    cssIso: '\\2194',
    jsOctal: '\\u2194',
    category: 'arrows'
  },
  {
    html: '&crarr;',
    symbol: '↵',
    numeric: '&#8629;',
    description: 'downwards arrow with corner leftwards, a.k.a. carriage return',
    hex: 'u+21B5 NEW',
    cssIso: '\\21B5',
    jsOctal: '\\u21b5',
    category: 'arrows'
  },
  {
    html: '&lArr;',
    symbol: '⇐',
    numeric: '&#8656;',
    description: 'leftwards double arrow can be used for ‘is implied by’',
    hex: 'u+21D0 ISOtech',
    cssIso: '\\21D0',
    jsOctal: '\\u21d0',
    category: 'arrows'
  },
  {
    html: '&uArr;',
    symbol: '⇑',
    numeric: '&#8657;',
    description: 'upwards double arrow',
    hex: 'u+21D1 ISOamsa',
    cssIso: '\\21D1',
    jsOctal: '\\u21d1',
    category: 'arrows'
  },
  {
    html: '&rArr;',
    symbol: '⇒',
    numeric: '&#8658;',
    description: 'rightwards double arrow',
    hex: 'u+21D2 ISOtech',
    cssIso: '\\21D2',
    jsOctal: '\\u21d2',
    category: 'arrows'
  },
  {
    html: '&dArr;',
    symbol: '⇓',
    numeric: '&#8659;',
    description: 'downwards double arrow',
    hex: 'u+21D3 ISOamsa',
    cssIso: '\\21D3',
    jsOctal: '\\ud1d3',
    category: 'arrows'
  },
  {
    html: '&hArr;',
    symbol: '⇔',
    numeric: '&#8660;',
    description: 'left right double arrow',
    hex: 'u+21D4 ISOamsa',
    cssIso: '\\21D4',
    jsOctal: '\\u21d4',
    category: 'arrows'
  },
  {
    html: '',
    symbol: '◄',
    numeric: '&#9668;',
    description: 'black left pointing triangle',
    hex: 'U+25C0',
    cssIso: '\\25C0',
    jsOctal: '\\u25c0',
    category: 'arrows'
  },
  {
    html: '',
    symbol: '►',
    numeric: '&#9658;',
    description: 'black right pointing triangle',
    hex: 'u+25B6',
    cssIso: '\\25b6',
    jsOctal: '\\u25b6',
    category: 'arrows'
  },
  {
    html: '',
    symbol: '▲',
    numeric: '&#9650;',
    description: 'black up pointing triangle',
    hex: 'u+25B2',
    cssIso: '\\25b2',
    jsOctal: '\\25b2',
    category: 'arrows'
  },
  {
    html: '',
    symbol: '▼',
    numeric: '&#9660;',
    description: 'black down pointing triangle',
    hex: 'u+25BC',
    cssIso: '\\25bc',
    jsOctal: '\\25bc',
    category: 'arrows'
  },
  {
    html: '&forall;',
    symbol: '∀',
    numeric: '&#8704;',
    description: 'for all',
    hex: 'u+2200 ISOtech',
    cssIso: '\\2200',
    jsOctal: '\\u2200',
    category: 'mathematical operators'
  },
  {
    html: '&part;',
    symbol: '∂',
    numeric: '&#8706;',
    description: 'partial differential',
    hex: 'u+2202 ISOtech',
    cssIso: '\\2202',
    jsOctal: '\\u2202',
    category: 'mathematical operators'
  },
  {
    html: '&exist;',
    symbol: '∃',
    numeric: '&#8707;',
    description: 'there exists',
    hex: 'u+2203 ISOtech',
    cssIso: '\\2203',
    jsOctal: '\\u2203',
    category: 'mathematical operators'
  },
  {
    html: '&empty;',
    symbol: '∅',
    numeric: '&#8709;',
    description: 'empty set, a.k.a. null set, a.k.a. diameter',
    hex: 'u+2205 ISOamso',
    cssIso: '\\2205',
    jsOctal: '\\u2205',
    category: 'mathematical operators'
  },
  {
    html: '&nabla;',
    symbol: '∇',
    numeric: '&#8711;',
    description: 'nabla, a.k.a. backward difference',
    hex: 'u+2207 ISOtech',
    cssIso: '\\2207',
    jsOctal: '\\u2207',
    category: 'mathematical operators'
  },
  {
    html: '&isin;',
    symbol: '∈',
    numeric: '&#8712;',
    description: 'element of',
    hex: 'u+2208 ISOtech',
    cssIso: '\\2208',
    jsOctal: '\\u2208',
    category: 'mathematical operators'
  },
  {
    html: '&notin;',
    symbol: '∉',
    numeric: '&#8713;',
    description: 'not an element of',
    hex: 'u+2209 ISOtech',
    cssIso: '\\2209',
    jsOctal: '\\u2209',
    category: 'mathematical operators'
  },
  {
    html: '&ni;',
    symbol: '∋',
    numeric: '&#8715;',
    description: 'contains as member',
    hex: 'u+220B ISOtech',
    cssIso: '\\220B',
    jsOctal: '\\u220b',
    category: 'mathematical operators'
  },
  {
    html: '&prod;',
    symbol: '∏',
    numeric: '&#8719;',
    description: 'n-ary product, a.k.a. product sign',
    hex: 'u+220F ISOamsb',
    cssIso: '\\220F',
    jsOctal: '\\u03a0',
    category: 'mathematical operators'
  },
  {
    html: '&sum;',
    symbol: '∑',
    numeric: '&#8721;',
    description: 'n-ary sumation',
    hex: 'u+2211 ISOamsb',
    cssIso: '\\2211',
    jsOctal: '\\u03a3',
    category: 'mathematical operators'
  },
  {
    html: '&minus;',
    symbol: '−',
    numeric: '&#8722;',
    description: 'minus sign',
    hex: 'u+2212 ISOtech',
    cssIso: '\\2212',
    jsOctal: '\\u2212',
    category: 'mathematical operators'
  },
  {
    html: '&lowast;',
    symbol: '∗',
    numeric: '&#8727;',
    description: 'asterisk operator',
    hex: 'u+2217 ISOtech',
    cssIso: '\\2217',
    jsOctal: '\\u2217',
    category: 'mathematical operators'
  },
  {
    html: '&radic;',
    symbol: '√',
    numeric: '&#8730;',
    description: 'square root, a.k.a. radical sign',
    hex: 'u+221A ISOtech',
    cssIso: '\\221A',
    jsOctal: '\\u221a',
    category: 'mathematical operators'
  },
  {
    html: '&prop;',
    symbol: '∝',
    numeric: '&#8733;',
    description: 'proportional to',
    hex: 'u+221D ISOtech',
    cssIso: '\\221D',
    jsOctal: '\\u221d',
    category: 'mathematical operators'
  },
  {
    html: '&infin;',
    symbol: '∞',
    numeric: '&#8734;',
    description: 'infinity',
    hex: 'u+221E ISOtech',
    cssIso: '\\221E',
    jsOctal: '\\u221e',
    category: 'mathematical operators'
  },
  {
    html: '&ang;',
    symbol: '∠',
    numeric: '&#8736;',
    description: 'angle',
    hex: 'u+2220 ISOamso',
    cssIso: '\\2220',
    jsOctal: '\\u2220',
    category: 'mathematical operators'
  },
  {
    html: '&and;',
    symbol: '⊥',
    numeric: '&#8869;',
    description: 'logical and, a.k.a. wedge',
    hex: 'u+2227 ISOtech',
    cssIso: '\\2227',
    jsOctal: '\\u2227',
    category: 'mathematical operators'
  },
  {
    html: '&or;',
    symbol: '⊦',
    numeric: '&#8870;',
    description: 'logical or, a.k.a. vee',
    hex: 'u+2228 ISOtech',
    cssIso: '\\2228',
    jsOctal: '\\u2228',
    category: 'mathematical operators'
  },
  {
    html: '&cap;',
    symbol: '∩',
    numeric: '&#8745;',
    description: 'intersection, a.k.a. cap',
    hex: 'u+2229 ISOtech',
    cssIso: '\\2229',
    jsOctal: '\\u2229',
    category: 'mathematical operators'
  },
  {
    html: '&cup;',
    symbol: '∪',
    numeric: '&#8746;',
    description: 'union, a.k.a. cup',
    hex: 'u+222A ISOtech',
    cssIso: '\\222A',
    jsOctal: '\\u222a',
    category: 'mathematical operators'
  },
  {
    html: '&int;',
    symbol: '∫',
    numeric: '&#8747;',
    description: 'integral',
    hex: 'u+222B ISOtech',
    cssIso: '\\222B',
    jsOctal: '\\u222b',
    category: 'mathematical operators'
  },
  {
    html: '&there4;',
    symbol: '∴',
    numeric: '&#8756;',
    description: 'therefore',
    hex: 'u+2234 ISOtech',
    cssIso: '\\2234',
    jsOctal: '\\u2234',
    category: 'mathematical operators'
  },
  {
    html: '&sim;',
    symbol: '∼',
    numeric: '&#8764;',
    description: 'tilde',
    hex: 'u+223C ISOtech',
    cssIso: '\\223C',
    jsOctal: '\\u223c',
    category: 'mathematical operators'
  },
  {
    html: '&cong;',
    symbol: '≅',
    numeric: '&#8773;',
    description: 'approximately equal to',
    hex: 'u+2245 ISOtech',
    cssIso: '\\2245',
    jsOctal: '\\u2245',
    category: 'mathematical operators'
  },
  {
    html: '&asymp;',
    symbol: '≈',
    numeric: '&#8776;',
    description: 'almost equal to, a.k.a. asymptotic to',
    hex: 'u+2248 ISOamsr',
    cssIso: '\\2248',
    jsOctal: '\\u2248',
    category: 'mathematical operators'
  },
  {
    html: '&ne;',
    symbol: '≠',
    numeric: '&#8800;',
    description: 'not equal to',
    hex: 'u+2260 ISOtech',
    cssIso: '\\2260',
    jsOctal: '\\u2260',
    category: 'mathematical operators'
  },
  {
    html: '&equiv;',
    symbol: '≡',
    numeric: '&#8801;',
    description: 'identical to',
    hex: 'u+2261 ISOtech',
    cssIso: '\\2261',
    jsOctal: '\\u2261',
    category: 'mathematical operators'
  },
  {
    html: '&le;',
    symbol: '≤',
    numeric: '&#8804;',
    description: 'less-than or equal to',
    hex: 'u+2264 ISOtech',
    cssIso: '\\2264',
    jsOctal: '\\u2264',
    category: 'mathematical operators'
  },
  {
    html: '&ge;',
    symbol: '≥',
    numeric: '&#8805;',
    description: 'greater-than or equal to',
    hex: 'u+2265 ISOtech',
    cssIso: '\\2265',
    jsOctal: '\\u2265',
    category: 'mathematical operators'
  },
  {
    html: '&sub;',
    symbol: '⊂',
    numeric: '&#8834;',
    description: 'subset of',
    hex: 'u+2282 ISOtech',
    cssIso: '\\2282',
    jsOctal: '\\u2282',
    category: 'mathematical operators'
  },
  {
    html: '&sup;',
    symbol: '⊃',
    numeric: '&#8835;',
    description: 'superset of',
    hex: 'u+2283 ISOtech',
    cssIso: '\\2283',
    jsOctal: '\\u2283',
    category: 'mathematical operators'
  },
  {
    html: '&nsub;',
    symbol: '⊄',
    numeric: '&#8836;',
    description: 'not a subset of',
    hex: 'u+2284 ISOamsn',
    cssIso: '\\2284',
    jsOctal: '\\u2284',
    category: 'mathematical operators'
  },
  {
    html: '&sube;',
    symbol: '⊆',
    numeric: '&#8838;',
    description: 'subset of or equal to',
    hex: 'u+2286 ISOtech',
    cssIso: '\\2286',
    jsOctal: '\\u2286',
    category: 'mathematical operators'
  },
  {
    html: '&supe;',
    symbol: '⊇',
    numeric: '&#8839;',
    description: 'superset of or equal to',
    hex: 'u+2287 ISOtech',
    cssIso: '\\2287',
    jsOctal: '\\u2287',
    category: 'mathematical operators'
  },
  {
    html: '&oplus;',
    symbol: '⊕',
    numeric: '&#8853;',
    description: 'circled plus, a.k.a. direct sum',
    hex: 'u+2295 ISOamsb',
    cssIso: '\\2295',
    jsOctal: '\\u2295',
    category: 'mathematical operators'
  },
  {
    html: '&otimes;',
    symbol: '⊗',
    numeric: '&#8855;',
    description: 'circled times, a.k.a. vector product',
    hex: 'u+2297 ISOamsb',
    cssIso: '\\2297',
    jsOctal: '\\u2297',
    category: 'mathematical operators'
  },
  {
    html: '&perp;',
    symbol: '⊥',
    numeric: '&#8869;',
    description: 'up tack',
    hex: 'u+22A5 ISOtech',
    cssIso: '\\22A5',
    jsOctal: '\\u22a5',
    category: 'mathematical operators'
  },
  {
    html: '&sdot;',
    symbol: '⋅',
    numeric: '&#8901;',
    description: 'dot operator',
    hex: 'u+22C5 ISOamsb',
    cssIso: '\\22C5',
    jsOctal: '\\u22c5',
    category: 'mathematical operators'
  },
  {
    html: '&lceil;',
    symbol: '⌈',
    numeric: '&#8968;',
    description: 'left ceiling, a.k.a. apl upstile',
    hex: 'u+2308 ISOamsc',
    cssIso: '\\2308',
    jsOctal: '\\u2308',
    category: 'technical'
  },
  {
    html: '&rceil;',
    symbol: '⌉',
    numeric: '&#8969;',
    description: 'right ceiling',
    hex: 'u+2309 ISOamsc',
    cssIso: '\\2309',
    jsOctal: '\\u2309',
    category: 'technical'
  },
  {
    html: '&lfloor;',
    symbol: '⌊',
    numeric: '&#8970;',
    description: 'left floor, a.k.a. apl downstile',
    hex: 'u+230A ISOamsc',
    cssIso: '\\230A',
    jsOctal: '\\u230a',
    category: 'technical'
  },
  {
    html: '&rfloor;',
    symbol: '⌋',
    numeric: '&#8971;',
    description: 'right floor',
    hex: 'u+230B ISOamsc',
    cssIso: '\\230B',
    jsOctal: '\\u230b',
    category: 'technical'
  },
  {
    html: '&lang;',
    symbol: '〈',
    numeric: '&#9001;',
    description: 'left-pointing angle bracket',
    hex: 'u+2329 ISOtech',
    cssIso: '\\2329',
    jsOctal: '\\u2329',
    category: 'technical'
  },
  {
    html: '&rang;',
    symbol: '〉',
    numeric: '&#9002;',
    description: 'right-pointing angle bracket',
    hex: 'u+232A ISOtech',
    cssIso: '\\232A',
    jsOctal: '\\u232a',
    category: 'technical'
  },
  {
    html: '&loz;',
    symbol: '◊',
    numeric: '&#9674;',
    description: 'lozenge',
    hex: 'u+25CA ISOpub',
    cssIso: '\\25CA',
    jsOctal: '\\u25ca',
    category: 'miscellaneous'
  },
  {
    html: '&spades;',
    symbol: '♠',
    numeric: '&#9824;',
    description: 'black spade suit',
    hex: 'u+2660 ISOpub',
    cssIso: '\\2660',
    jsOctal: '\\u2660',
    category: 'miscellaneous'
  },
  {
    html: '&clubs;',
    symbol: '♣',
    numeric: '&#9827;',
    description: 'black club suit, a.k.a. shamrock',
    hex: 'u+2663 ISOpub',
    cssIso: '\\2663',
    jsOctal: '\\u2663',
    category: 'miscellaneous'
  },
  {
    html: '&hearts;',
    symbol: '♥',
    numeric: '&#9829;',
    description: 'black heart suit, a.k.a. valentine',
    hex: 'u+2665 ISOpub',
    cssIso: '\\2665',
    jsOctal: '\\u2665',
    category: 'miscellaneous'
  },
  {
    html: '&diams;',
    symbol: '♦',
    numeric: '&#9830;',
    description: 'black diamond suit',
    hex: 'u+2666 ISOpub',
    cssIso: '\\2666',
    jsOctal: '\\u2666',
    category: 'miscellaneous'
  }
];
